version: '3.1'

volumes:
  db_data: {}

services:
  db:
    image: postgres:15.4-bookworm
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_passwd
    volumes:
      - ./secrets/postgres_passwd:/run/secrets/postgres_passwd:ro
      - db_data:/var/lib/postgresql
    ports:
      - 5432:5432